language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - npm i @microservices/cli

script:
  - npx oms build
  - |
    output="$(npx oms run --silent transcribe \
      -a url=https://oms.hudson.dev/fixtures/speech.wav \
      -a speakerLabels=false \
      -a smartFormatting=false | jq -c .)"
    if [ "$output" != '{"results":[{"alternatives":[{"confidence":0.99,"transcript":"thunderstorms could produce large hail isolated tornadoes and heavy rain "}],"final":true}],"result_index":0}' ] ; then echo "$output"; exit 1; fi
